### PR TITLE
add token only if not present, also to `fileURL` parameters

### PR DESCRIPTION
**Pull request by burnout87**

### CODE REVIEW

**Review by dsavchenko — APPROVED** [review]

**Comment by burnout87** [comment]
As described here https://github.com/oda-hub/dispatcher-app/pull/719#issue-2672037878 , the token willbe added in the following cases:

* the parameter is a FileReference, a POSIXPath or a FileURL
* the parameter is a valid URL
* the parameter is also an mmoda URL

Eventually, the parameter will be downloaded only if this is a POSIXPath

**Review by dsavchenko — APPROVED** [review]

**Comment by burnout87** [comment]
can you please merge @volodymyrss  ?

**Comment by dsavchenko** [comment]
Don't merge it. We are discussing additional cases

**Comment by burnout87** [comment]
Now it is additionally checking the `FileURL` type, and issuing a `ValueError` exception in case a not-url arg is passed in the query

**Review by volodymyrss — APPROVED** [review]

**Review by dsavchenko — APPROVED** [review]

**Comment by burnout87** [comment]
> can you please merge @volodymyrss ?

Now @volodymyrss  can merge

**Pull request merged**
