### PR TITLE
arg get request opens notebook

### PR DESCRIPTION
**Pull request by burnout87**

### CODE REVIEW

**Comment by burnout87** [comment]
The `'/trace/<string:job>/<string:func>'` endpoint now reads an arg that tells whether or not the cell with the output glueing should be present within the output html, default is to include the glueing to preserve the current behavior.

The problem is that this parameter cannot be passed from the `get_progress_run` function. Can this be configured somewhere else?

**Review by dsavchenko — CHANGES_REQUESTED** [review]
Not sure if BeautifulSoup is already a sub-requirement, but better to explicitly add it to 'service' extra

**Comment by volodymyrss** [comment]
Thanks, looks good in principle, but it fails because of:

```python
 FileNotFoundError: [Errno 2] No such file or directory: '/tmp/nb2w-3051c2zi/workflow-notebook_output.ipynb'
```

**Comment by burnout87** [comment]
there are currently issues in running the workflow, it simply does not start

**Comment by volodymyrss** [comment]
> there are currently issues in running the workflow, it simply does not start

What do you mean?

**Comment by burnout87** [comment]
> > there are currently issues in running the workflow, it simply does not start
> 
> What do you mean?

https://github.com/oda-hub/nb2workflow/actions/runs/8112936999/job/22175870169

the job does not start

**Review by dsavchenko — APPROVED** [review]

**Comment by burnout87** [comment]
can you merge this ?

**Comment by volodymyrss** [comment]
> can you merge this ?

I can!

**Pull request merged**
