### PR TITLE
Mmoda validation

### PR DESCRIPTION
**Pull request by volodymyrss**

### CODE REVIEW

**Comment by dsavchenko** [comment]
I thought we agreed not to import the plugin, but to implement checks in oda_api data product.
This will also work, but let's coincide on the way to do it.

PS: sorry, I'm not very active these days

**Comment by volodymyrss** [comment]
> I thought we agreed not to import the plugin, but to implement checks in oda_api data product. This will also work, but let's coincide on the way to do it.

We agreed based on what we knew at that time. 
After looking more closely in the plugin implementation, it is clear that there is lots of functionality related to parsing the options and the outputs which would be nice to validate too.
It would be nicer to avoid depending on the plugin, but there is a bit too much relevant content in it. And unless it can be completely taken out to another project, the plugin has to be imported in the validation

I do not really see another way to achieve it, do you?

**Comment by volodymyrss** [comment]
> Ok, let's move this way. Anyway, this validation is closely related to the plugin.

it works now, during `nbrun`. There is one issue - with loading config, which is not needed in this case. I will propose something  I guess.

**Comment by volodymyrss** [comment]
combined into #46

**Pull request closed without merging**
