### PR TITLE
Use renku base image

### PR DESCRIPTION
**Pull request by dsavchenko**

### CODE REVIEW

**Comment by volodymyrss** [comment]
There is a complexity with renku image, it's delicate. 
In fact, Dockerfile in renku image is not even guaranteed to start a session, let alone do any good for MODA service.

Apparently renku assumes, by convention, that the latter part of the Dockerfile can be modified by the user. While the top should be kept unchanged.

We can do something similar, add to our Dockerfile the second part of the renku dockerfile.
As one of the options. This is likely to be a more predicable.

However, all of the Dockerfile modifications should be seen as advanced-user best-to-avoid approach.

**Comment by dsavchenko** [comment]
> However, all of the Dockerfile modifications should be seen as advanced-user best-to-avoid approach.

That's true. But I came to implementing this following Oleg's attempt to install needed system packages by adding apt-get calls in the Dockerfile. (It's often possible to use conda environment in such cases, but at the time, due to some change on renku side, any environment.yml with the "default" channel resulted in the build timeout). 
Still, we have the (undocumented) option in the bot to use Dockerfile from the repo as a base and some logic to handle it is already there. It doesn't work as expected, though. The default behaviour is to build from micromamba, and it should be kept default and recommended, unless we want to make use of the renku plugin in the service.

**Comment by dsavchenko** [comment]
The main complication here is that the Dockerfile instructions on renku assume that the build context is in the repo root. In nb2deploy we clone the repo into the subfolder (and in the kaniko mode of operation, used by the bot, it's actually cloned there on build). 
In this PR I started to change the location of the build context folder. But it has to be mounted by the kaniko job as a volume, that's the complication. 

Another way, that could be preferential, is to use not the Dockerfile from the repo, but the actual container image built by renku CI/CD as a base image.

**Comment by volodymyrss** [comment]
> That's true. But I came to implementing this following Oleg's attempt to install needed system packages by adding apt-get calls in the Dockerfile. (It's often possible to use conda environment in such cases, but at the time, due to some change on renku side, any environment.yml with the "default" channel resulted in the build timeout).

I think most of the time it is. If not, conda package can be made. If some weird customization is needed, expert is needed anyway.

In the case of Oleg (and @andriineronov ) I talked to them and indeed they could solve it without Dockerfile modification. In fact, it got solved magically somehow.

> Still, we have the (undocumented) option in the bot to use Dockerfile from the repo as a base and some logic to handle it is already there. It doesn't work as expected, though. The default behaviour is to build from micromamba, and it should be kept default and recommended, 

> unless we want to make use of the renku plugin in the service.

this is interesing, I think we want to use renku plugin when running job (there is even [an issue](https://github.com/oda-hub/nb2workflow/issues/47)), to track service requests, other metadata. But, this would be run around the user notebook. So user would not access it in the notebook, and renku could be installed as bot's "standard" packages.

If, however, user uses renku explicitly in the notebook, there might be also constrain on renku version. We do not really do this at the moment so it does not matter so much.

> The main complication here is that the Dockerfile instructions on renku assume that the build context is in the repo root. In nb2deploy we clone the repo into the subfolder (and in the kaniko mode of operation, used by the bot, it's actually cloned there on build). In this PR I started to change the location of the build context folder. But it has to be mounted by the kaniko job as a volume, that's the complication.

maybe this makes sense, need to look into it
 
> Another way, that could be preferential, is to use not the Dockerfile from the repo, but the actual container image built by renku CI/CD as a base image.

it will have things which we do not need like jupyterlab and even other UI-related stuff not relevant for service operation like  vnc in [euclid image](https://gitlab.renkulab.io/astronomy/mmoda/photoz-euclid/-/blob/master/Dockerfile). 

The idea is that the tool itself is defined by requirements/environment.yml + repo files. And this tool definition can be customized into service image, renku ui image, batch image (see nb2cwl), etc.
Also, service image, for example, can be re-composed with new nb2workflow to enable some service new features even when the science code is unchanged. 
This way user builds container without thinking about making entrypoint, env, other container details which are tricky for users. 

It's true that there might be issues re-building as service/batch container, but we know it was built as renku jupyterlab ui, so we know we can practically always create the needed variation.  

However, sometimes it would be reasonable to just replace entrypoint. Maybe this can be kept as an option too.

Nb2workflow updates can be handled better if it is not installed on top of the science logic. 
That's why there is nb2cwl which creates a batch-friendly image which can be submitted to reana (CERN), calrissian (like at ESA) or just as k8s job.
However, there still needs to be nb2workflow inside the container to  wrap papermill and help user to format outputs. But, in this case, version of nb2workflow might not to change as much, and the same version user used can be kept.
To make use of this approach as a service, nb2service would need to be able to delegate the execution elsewhere ([issue](https://github.com/oda-hub/nb2workflow/issues/11)) and only act as a proxy. This would allow larger load too. Also multiple nb2services could be replaces with just one, while preserving the functionality. But since, at this point, this does not add too much in practice, that's why I did not progress on this direction enough (except for running many jobs with nb2cwl triggered from elsewhere).

So I propose for now to stick to conda as much as feasible, and if we really find a showstopper, then use these advanced options like using renkulab Dockerfile (or part of it) with upgraded nb2workflow (probably always necessary eventually) or even using the entire renkulab image with replaced entrypoint. But, for now, is there any concrete need for this?

**Pull request closed without merging**
